/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppConnect {
    }
    interface AppHome {
    }
    interface AppMembers {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
}
declare global {
    interface HTMLAppConnectElement extends Components.AppConnect, HTMLStencilElement {
    }
    var HTMLAppConnectElement: {
        prototype: HTMLAppConnectElement;
        new (): HTMLAppConnectElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMembersElement extends Components.AppMembers, HTMLStencilElement {
    }
    var HTMLAppMembersElement: {
        prototype: HTMLAppMembersElement;
        new (): HTMLAppMembersElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {
    }
    var HTMLAppSettingsElement: {
        prototype: HTMLAppSettingsElement;
        new (): HTMLAppSettingsElement;
    };
    interface HTMLElementTagNameMap {
        "app-connect": HTMLAppConnectElement;
        "app-home": HTMLAppHomeElement;
        "app-members": HTMLAppMembersElement;
        "app-root": HTMLAppRootElement;
        "app-settings": HTMLAppSettingsElement;
    }
}
declare namespace LocalJSX {
    interface AppConnect {
    }
    interface AppHome {
    }
    interface AppMembers {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface IntrinsicElements {
        "app-connect": AppConnect;
        "app-home": AppHome;
        "app-members": AppMembers;
        "app-root": AppRoot;
        "app-settings": AppSettings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-connect": LocalJSX.AppConnect & JSXBase.HTMLAttributes<HTMLAppConnectElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-members": LocalJSX.AppMembers & JSXBase.HTMLAttributes<HTMLAppMembersElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-settings": LocalJSX.AppSettings & JSXBase.HTMLAttributes<HTMLAppSettingsElement>;
        }
    }
}
